### PR TITLE
Fix some bugs in the notebook

### PR DESCRIPTION
**Pull request by jlewi**
* Need to install matplotlib if not installed
* Looks like there were some spurious cells that weren't running and
  were no longer used.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/reporting/4)

### CODE REVIEW

**Comment by jlewi** [comment]
Test's aren't running 

```
INFO|2019-07-23T03:49:30|/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py|159| File kubeflow-stats.ipynb is modified.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py", line 418, in <module>
    final_result = main()
  File "/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py", line 408, in main
    return run(args, file_handler)
  File "/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py", line 165, in run
    workflows.extend(parse_config_file(args.config_file, args.repos_dir))
  File "/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py", line 87, in parse_config_file
    with open(config_file) as hf:
IOError: [Errno 2] No such file or directory: '/src/kubeflow/reporting/prow_config.yaml'
```

**Comment by abhi-g** [comment]
Is the prow_config.yaml actually missing or the tests are just not able to
find it?

**Comment by jlewi** [comment]
prow_config.yaml doesn't exist and looks like it never did. I'm not sure what changed.

**Comment by jlewi** [comment]
No idea why the pull request was closed.

**Comment by jlewi** [comment]
It looks like it got closed because I rebased and that removed all the files from the PR.

**Comment by jlewi** [comment]
I restored the files by checking out 6be798d  and force pushing that. At that point I was able to reopen the pull request.

**Comment by jlewi** [comment]
Here are the logs from the prow job

```
+ /usr/local/bin/checkout.sh /src
+ SRC_DIR=/src
+ mkdir -p /src/kubeflow
+ git clone --depth=2 --no-single-branch https://github.com/kubeflow/reporting.git /src/kubeflow/reporting
Cloning into '/src/kubeflow/reporting'...
+ echo Job Name = kubeflow-reporting-presubmit
Job Name = kubeflow-reporting-presubmit
+ REPO_DIR=/src/kubeflow/reporting
+ cd /src/kubeflow/reporting
+ '[' '!' -z 4 ']'
+ git fetch origin pull/4/head:pr
From https://github.com/kubeflow/reporting
 * [new ref]         refs/pull/4/head -> pr
+ '[' '!' -z 71a388b2074b9c84afbf287e0d1efab8df62dff8 ']'
+ git checkout 71a388b2074b9c84afbf287e0d1efab8df62dff8
Note: checking out '71a388b2074b9c84afbf287e0d1efab8df62dff8'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 71a388b... Merge pull request #3 from jlewi/spartakus_report
+ git submodule init
+ git submodule update
++ git describe --tags --always --dirty
/src/kubeflow/reporting is at 71a388b
+ echo /src/kubeflow/reporting is at 71a388b
+ git submodule
+ git status
HEAD detached at 71a388b
nothing to commit, working directory clean
+ IFS=';'
+ read -ra REPOS
REPOS=
+ echo REPOS=
+ '[' '!' -d /src/kubeflow/testing ']'
+ git clone --depth=1 https://github.com/kubeflow/testing.git /src/kubeflow/testing
Cloning into '/src/kubeflow/testing'...
+ python -m kubeflow.testing.run_e2e_workflow --project=kubeflow-ci --zone=us-east1-d --cluster=kubeflow-testing --bucket=kubernetes-jenkins --config_file=/src/kubeflow/reporting/prow_config.yaml --repos_dir=/src
INFO|2019-09-04T00:41:12|/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py|406| Logging to /tmp/tmpRunE2eWorkflowWOdBIVlog
INFO|2019-09-04T00:41:12|/src/kubeflow/testing/py/kubeflow/testing/util.py|45| Running: git fetch origin master:refs/remotes/origin/master 
cwd=/src/kubeflow/reporting
INFO|2019-09-04T00:41:12|/src/kubeflow/testing/py/kubeflow/testing/util.py|60| Subprocess output:

INFO|2019-09-04T00:41:13|/src/kubeflow/testing/py/kubeflow/testing/util.py|45| Running: git merge-base HEAD remotes/origin/master 
cwd=/src/kubeflow/reporting
INFO|2019-09-04T00:41:13|/src/kubeflow/testing/py/kubeflow/testing/util.py|60| Subprocess output:

INFO|2019-09-04T00:41:13|/src/kubeflow/testing/py/kubeflow/testing/util.py|82| 71a388b2074b9c84afbf287e0d1efab8df62dff8
INFO|2019-09-04T00:41:13|/src/kubeflow/testing/py/kubeflow/testing/util.py|45| Running: git diff --name-only 71a388b2074b9c84afbf287e0d1efab8df62dff8 
cwd=/src/kubeflow/reporting
INFO|2019-09-04T00:41:13|/src/kubeflow/testing/py/kubeflow/testing/util.py|60| Subprocess output:

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py", line 418, in <module>
    final_result = main()
  File "/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py", line 408, in main
    return run(args, file_handler)
  File "/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py", line 165, in run
    workflows.extend(parse_config_file(args.config_file, args.repos_dir))
  File "/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py", line 87, in parse_config_file
    with open(config_file) as hf:
IOError: [Errno 2] No such file or directory: '/src/kubeflow/reporting/prow_config.yaml'
```
So its complaining about prow_config.yaml missing.

Why is it checking out commit 71a388b2074b9c84afbf287e0d1efab8df62dff8

**Comment by jlewi** [comment]
https://github.com/kubeflow/reporting/commit/71a388b2074b9c84afbf287e0d1efab8df62dff8 is the most recent commit to master. 

I wonder if the fact that the remote branch is named master is causing problems?

**Comment by jlewi** [comment]
https://github.com/kubeflow/testing/blob/4becffa00b08b94d9cd00803a934180d9350af5a/images/checkout.sh#L41

So its calling

```
git checkout ${PULL_PULL_SHA}
```

**Comment by jlewi** [comment]
Looks like that is a red herring. That was the PR run for 71a388b when I reverted everything.

**Comment by jlewi** [comment]
Here's is the most recent failure.

```
INFO|2019-09-04T01:07:49|/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py|159| File prow_config.yaml is modified.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py", line 418, in <module>
    final_result = main()
  File "/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py", line 408, in main
    return run(args, file_handler)
  File "/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py", line 165, in run
    workflows.extend(parse_config_file(args.config_file, args.repos_dir))
  File "/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py", line 91, in parse_config_file
    for i in results["workflows"]:
TypeError: 'NoneType' object is not iterable
```

**Comment by jlewi** [comment]
@abhi-g tests are passing now; could you take another look please?

**Pull request merged**
